baseURL: /
languageCode: en-us
title: fc-dev
theme: hello-friend-ng
paginate: 10

author:
  name: Fede Capece
 
#allow for raw html
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  # Subtitle for home
  homeSubtitle: Depressed developer

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts: false
  
  # Enable sharing buttons, if you linke
  enableSharingButtons: true

  
  # Metadata mostly used in document's head
  description: fc-dev
  keywords: 'homepage, blog'
  images:
    - ''
  
  # Default theme "light" or "dark"
  defaultTheme: dark

  #logo
  logo:
    logoText: root@fc-dev
    logoCursorColor: grey
    logoAfterMark: :~#
  
  #homepage image
  portrait:
    path: /img/fc-dev.png
    alt: Portrait
    maxWidth: 350px

  #social link
  social:
    #- name: twitter
    #  url: 'https://twitter.com/gamedev_cutie'
    - name: email
      url: 'mailto:feddycap97@gmail.com'
    - name: github
      url: 'https://github.com/fcdev'
    - name: linkedin
      url: 'https://www.linkedin.com/in/federicocapece/'
    - name: stackoverflow
      url: 'https://stackoverflow.com/users/4698299'
    #- name: instagram
    #  url: 'https://instagr.am/gamedev_cutie'

#weird shit
taxonomies:
  category: blog
  tag: tags
  series: series
