baseURL 		= "/"
languageCode	= "en-us"
title 			= "fc-dev"
theme 			= "hello-friend-ng"
paginate     	= 10

[params]
  # Subtitle for home
  homeSubtitle = "Depressed developer :D"


  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [params.logo]
      logoText = "root@fc-dev"
      logoCursorColor = "grey"
  
  # Uncomment this if you want a portrait on your start page
   [params.portrait]
     path     = "/img/fc-dev.png"
     alt      = "Portrait"
     maxWidth = "350px"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/gamedev_cutie"

  [[params.social]]
    name = "email"
    url  = "mailto:feddycap97@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/fc-dev"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/federicocapece/"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/4698299"

  [[params.social]]
    name = "instagram"
    url  = "https://instagr.am/gamedev_cutie"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    #footer copyright
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'


